encoder_odometry:
  ros__parameters:
    publish_tf: false
    odom_publish_rate_hz: 100.0
    odom_topic: /odom/encoder
    path_publish_rate_hz: 5.0
    path_min_distance: 0.02
    path_max_length: 2000
    max_dt_sec: 0.2
    encoder_timeout_sec: 0.1
    odom_frame_id: odom
    base_frame_id: base_link
    heading_rad: 0.0

encoder_imu_odometry:
  ros__parameters:
    publish_tf: false
    odom_publish_rate_hz: 100.0
    path_publish_rate_hz: 5.0
    path_min_distance: 0.02
    path_max_length: 2000
    max_dt_sec: 0.2
    encoder_timeout_sec: 0.1
    sensor_timeout_sec: 0.2
    odom_frame_id: odom
    base_frame_id: base_link
    imu_offset_x: 0.0
    heading_topic: imu/gyro_angle/z
